### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by mtnoztrk** [vutoan266/react-images-uploading#10]
Hello, 
In my recent project, I need to upload videos too. I used this library in one of my previous project and liked it. So I will fork and try to implement video file support. Are you interested in this? @vutoan266

**Comment by vutoan266** [comment]
Hello,
I am very happy to hear my lib is helpful for you. And it is very interesting if you done a library support upload video like my implement pattern. Maybe "react-video-uploading" for your folk repo.
Let me know if finish.
