### ISSUE TITLE
Replace existing image with the newly selected one.

### ISSUE THREAD

**Issue by Gunner17** [vutoan266/react-images-uploading#102]
Hi all,

I want to allow users upload one image at a time and also, when user selects/uploads a new image, if there is any previously selected image present, then that should get replaced with the new one. Is there any way to achieve that?

Thanks in advance.

**Comment by vutoan266** [comment]
Hi @Gunner17,

Sure you can do that. By the way set `maxNumber = 1`, when the user uploads the first image, use `onImageUpload` function, then latter uploading times, use `() => onImageUpdate(0)` to replace on the first one.

Hope it is helpful for you!

**Comment by 0xWWW** [comment]
You can try with the image uploaded latest with this snippet: imageList[imageList.length - 1]?.data_url
