### ISSUE TITLE
Could not resolve dependency: peer react@"^16.8.0" from react-images-uploading@3.1.3

### ISSUE THREAD

**Issue by levelingup** [vutoan266/react-images-uploading#107]
Getting error when trying to update my packages.
Is it because I'm using React 17.0.2, and this package is using React 16.8.0?

**Comment by Revolt9k** [comment]
any update with this?

**Comment by vutoan266** [comment]
Hi all, thanks for your reporting and workaround. I have just upgraded the peerDepedency of react/react-dom version. Please update to react-images-uploading@3.1.5
Thank you a lot!
