### ISSUE TITLE
[Feature Request] Require Drag and Drop support for uploading images

### ISSUE THREAD

**Issue by boopeshmahendran227** [vutoan266/react-images-uploading#11]
Thanks for creating this great library. 

In my current project, I need a feature where in the user should be able to drop files on a target to upload files. I tried to implement drag and drop feature myself, but I couldn't find a way to update the images list with the dropped files. So It would be great If you could expose some prop for doing this. 

Also, It would be awesome if this library itself provides drag and drop image upload support.

Thanks.

**Comment by vutoan266** [comment]
Hi @boopeshmahendran227, thanks for your suggestion.
I am very happy to announce that the component supported Drag and Drop feature. Please check out https://github.com/vutoan266/React-images-uploading for usage.
