### ISSUE TITLE
Issue while installing 

### ISSUE THREAD

**Issue by me-ibad** [vutoan266/react-images-uploading#120]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-test@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-images-uploading@3.1.3

**Comment by MichaelVandi** [comment]
Did you run install with ```--legacy-peer-deps```

**Comment by vutoan266** [comment]
Hi @me-ibad and @MichaelVandi , thanks for your reporting. I have just upgraded the peerDepedency of react/react-dom version. Please update to react-images-uploading@3.1.5
Thank you alot!
