### ISSUE TITLE
Image selector menu not opening on android device

### ISSUE THREAD

**Issue by plaporte** [vutoan266/react-images-uploading#128]
I have a react app that I'm using this plugin with. This is displayed within a webview on android and ios devices. iOS opens the context menu to select an image when firing 'onImageUpload', however nothing happens when I fire the function on android. Any help?

**Comment by jmcoder1** [comment]
Did you resolve this? I have the same problem?

**Comment by SteveLai524** [comment]
I have the same problem. may you due with it?


> Did you resolve this? I have the same problem?
