### ISSUE TITLE
Update docs readme

### ISSUE THREAD

**Issue by vutoan266** [vutoan266/react-images-uploading#18]
- Brief introduction
- Logo if it has
- Installation
- Usage: provides links to codesandbox with JS & TS, Server side & snippet of code
- Development: provides commands to start dev env or production env
- Props

**Comment by davidnguyen179** [comment]
Use this one to check the typo https://www.grammarly.com/

**Comment by vutoan266** [comment]
https://github.com/vutoan266/react-images-uploading/pull/28
