### ISSUE TITLE
Add tslint to validate code & command in package.json

### ISSUE THREAD

**Issue by davidnguyen179** [vutoan266/react-images-uploading#25]
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md

**Comment by conandk** [comment]
Currently, I'm using `airbnb-typescript` rule for eslint config. We need to discuss some issues to match this rule.

1. https://eslint.org/docs/rules/no-continue
    
<img width="333" alt="image" src="https://user-images.githubusercontent.com/12934183/93290647-64576800-f80b-11ea-82e4-9eacf0955127.png">

2. https://eslint.org/docs/rules/no-await-in-loop
<img width="412" alt="image" src="https://user-images.githubusercontent.com/12934183/93290766-a7b1d680-f80b-11ea-9d33-9be86c4077cd.png">

3. https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md
<img width="278" alt="image" src="https://user-images.githubusercontent.com/12934183/93290849-dcbe2900-f80b-11ea-820d-ad0981a0974f.png">

4. https://eslint.org/docs/rules/no-unused-expressions
<img width="455" alt="image" src="https://user-images.githubusercontent.com/12934183/93290897-f3648000-f80b-11ea-8b48-48653ae5a225.png">


@davidnguyen179 @vutoan266

**Comment by davidnguyen179** [comment]
1. We can keep continue
2. This syntax is a bit weird @vutoan266 , can you search the substitution?
3. We actually don't need that
4. We can keep
