### ISSUE TITLE
OnChange element can't catch element?

### ISSUE THREAD

**Issue by TRUEND** [vutoan266/React-images-uploading#3]
I'm trying to do something like this 

```
const onChange(image, e)=>
{
 //"e" is undefined;
}

<ImageUploading defaultValue={[{dataURL:Image}]} onChange={(e)=>onChange(e)} multiple={false} />
```
Any thoughts? why I can't get the element ? to do something like e.target.?

**Comment by vutoan266** [comment]
Hi @TRUEND why you need event attribute? Do you want to catch new selected images?

**Comment by TRUEND** [comment]
I needed to catch attributes data-* , but I figured it out in another way, I put the event on the buttons to upload new image and everything worked just fine. but it'd be nicer if I had event. thanks for you help, and really good job on this package 👍 .
