### ISSUE TITLE
Default value can be set only once

### ISSUE THREAD

**Issue by toto22450** [vutoan266/React-images-uploading#4]
Hello,

Great component that separate UI and logic :)

But I'm experience issue with the `defaultValue` attribute : it can be set only once. After the first initialisation the preview does not change, so I force the component to recreate by setting `key={defaultValue}` which is bad for performance concern.
Is there a proper workaround or is this a bug ?

Regards

**Comment by vutoan266** [comment]
Hi @toto22450, the only one purpose of defaultValue is it is value for initial at first mounting, so it's not a bug.
Why do you need your defaultValue change? I think you should make defaultValue available before the component is rendered.

**Comment by toto22450** [comment]
Hi @vutoan266, thanks for the answer

> Why do you need your defaultValue change?

I have a single form that can be filled by different data object after rendering.

> Why do you need your defaultValue change? I think you should make defaultValue available before the component is rendered.

That's true for the first object loading but not for the following ones

**Comment by adrian410** [comment]
It would be great to rather have a prop "value" to change the image from the outside.

**Comment by vutoan266** [comment]
Early day I code this, my expectation is one-way data: the component is not receive "value" props, but the component will have its state to manage data, and export outside by onChange function. I do it be cause I want my component handle all logic add/update/delete images, if receiving value it is so hard to do this, and facing performance issue in each rendering.

**Comment by vutoan266** [comment]
> Hi @vutoan266, thanks for the answer
> 
> > Why do you need your defaultValue change?
> 
> I have a single form that can be filled by different data object after rendering.
> 
> > Why do you need your defaultValue change? I think you should make defaultValue available before the component is rendered.
> 
> That's true for the first object loading but not for the following ones

I get your problem. In my case when I using this component, I will unmount form after finish editing session so it not happen your issue. Maybe this component is not good for your case. 
Let me know if you have any ideas.

**Comment by toto22450** [comment]
Ok thanks for your feedback, I will keep the workaround that I implemented !
