### ISSUE TITLE
Errors on UseRef$1 and Invariant Violation

### ISSUE THREAD

**Issue by veinhuang** [vutoan266/React-images-uploading#5]
Hi there, first of all, thank you for building out this library as it will be a great help!

I'm basically copying your Example component and trying to see if it works on my app. I'm getting these errors and the component does not show up at all. Just wondering if I don't have the right requirements to use this.

I'm on React version 15.5.4. Not sure if that matters. What am I doing wrong?

![Screen Shot 2020-05-06 at 11 08 39 PM](https://user-images.githubusercontent.com/38489711/81260276-884da600-8fee-11ea-9754-5a0a8ee8134a.png)

**Comment by vutoan266** [comment]
hi @veinhuang , your react version is out of date, not include hook API used in the component. You should update to v16.8 or upper.

**Comment by veinhuang** [comment]
oh, I didn't know this required a certain React version. 

Unfortunately, the app that my company app is on is a pretty big one and has been working on it for a few years so upgrading is not so easy (lots of breaking changes if React is upgraded). Would you happen to know another package that has similar functionality like yours?

**Comment by vutoan266** [comment]
Sorry for lately reply. I have not seen any image uploading component function likely so I made one. You can try with some other popular components on Npm. Good luck.
