### ISSUE TITLE
How to get(init) and display file from sever?

### ISSUE THREAD

**Issue by mtr1990** [vutoan266/React-images-uploading#6]
Hi Toan, 
I have try with Init file but this not working,
I'm use react hook 

This is my sandbox 
https://codesandbox.io/s/react-images-uploading-demo-62x8w?file=/src/index.js

Let me know where I was wrong, Thanks!

**Comment by vutoan266** [comment]
Hi @mtr1990, I cannot open the link. Can you check it or pass your code here.

**Comment by vutoan266** [comment]
HI @mtr1990 , I cannot open the link. Can you check it or pass your code here.
