### ISSUE TITLE
acceptType is case sensitive

### ISSUE THREAD

**Issue by AviKKi** [vutoan266/react-images-uploading#60]
acceptType attribute is case sensitive, which is a bit bad user experience for users who upload files with extension JPG or PNG. 

A quick fix is to include uppercase extensions, like
```jsx
acceptType={['jpg', 'png', 'jpeg', 'JPG', 'PNG', 'JPEG']}
```

But extension comparison should be case insensitive by default and allow case sensitive checking by a boolean Prop like

```jsx
acceptType={['jpg', 'png', 'jpeg']}
isCaseSensitive={true}
```

Let me know if this makes sense, I would love to contribute.

**Comment by davidnguyen179** [comment]
it was fixed by this PR https://github.com/vutoan266/react-images-uploading/pull/64

**Comment by AviKKi** [comment]
I'm closing the issue since it's been solved.
