### ISSUE TITLE
No way to set the "capture" attribute on the file input.

### ISSUE THREAD

**Issue by philip-nicholls** [vutoan266/react-images-uploading#71]
Since this component wraps the file input, there should be a way of passing through other html attributes to the file input such as "capture".

https://www.w3.org/TR/html-media-capture/#the-capture-attribute

Thanks

**Comment by vutoan266** [comment]
Hi, thanks for your feedback. We have made the [PR](https://github.com/vutoan266/react-images-uploading/pull/80) to resolve it.
