### ISSUE TITLE
paramater onError at props

### ISSUE THREAD

**Issue by kuzanto** [vutoan266/react-images-uploading#8]
Hello,

Can I get error value at props parameter like onError than at exported options? Because sometimes we need to get have custom error like with popup or modal or alert than just free text.

Thank you,
Regards

**Comment by vutoan266** [comment]
Hi Kuzato,
Sorry for too late reply to you. I have considered about your suggestion and workaround in my working. So I think it is necessary to have an onError function to trigger each validation has errors.
Thank you for your suggest. Have a nice day.
