### ISSUE TITLE
i need examlple for use onError props and errors

### ISSUE THREAD

**Issue by arezookhrirabedi** [vutoan266/react-images-uploading#83]
i search so but i coudent fined any example for check validation.i ll be so satisfied if u send me an example code

**Comment by jayeshmemorres** [comment]
hello Did you solve it yet?
if solved please help me.

**Comment by vutoan266** [comment]
Hi @arezookhrirabedi , @jayeshmemorres ,
This is my draft demo about validation, you should check it: [codesandbox](https://codesandbox.io/s/react-images-uploading-demo-validation-2ss2h)
Feel free to ask me if you have any questions. Thanks!
