### ISSUE TITLE
NoModificationAllowedError: Modifications are not allowed for this document Firefox

### ISSUE THREAD

**Issue by mehmetakify** [vutoan266/react-images-uploading#86]
In only Firefox and drag & drop it causes this error. It is common issue in Firefox with drag and drops. Could you please solve it?

**Comment by AsminBudha** [comment]
Got same issue with implementation provided in Readme.

**Comment by vutoan266** [comment]
Thanks for your feedback. Please check [PR](https://github.com/vutoan266/react-images-uploading/pull/91)
