### ISSUE TITLE
How to set images by default in value

### ISSUE THREAD

**Issue by esdras-assikid** [vutoan266/react-images-uploading#87]
I need to made a modify page so i fetch image from api and i want to set it by default in value of the ImageUploading componement. I get this error : 
Uncaught TypeError: Failed to construct 'Image': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
Is there a way to set images by default for ImageUploading ?

**Comment by vutoan266** [comment]
Hi @esdras-assikid,
You could set an initial image list like this (react hook example):
```
const [images, setImages] = useState([
   { dataURL: your_init_image_url_1 },
   { dataURL: your_init_image_url_1 },
   ...
]);
```
Thanks!
