### ISSUE TITLE
Preview of uploaded images don't show up

### ISSUE THREAD

**Issue by Shreykhanna** [vutoan266/react-images-uploading#88]
After uploading images when you go back again to upload images then the **preview of images** to be uploaded don't show up.
What I felt was that the code to show the **preview don't render again** because in **console.log th**e **imageList** **shows up to be empty**

**Note : Images do get uploaded  on submitting.**

**Comment by vutoan266** [comment]
Hi @Shreykhanna , sr for late reply. 
In your case, you have to make sure that the `value` prop contains the uploaded image. Example:
```
<ImageUploading value={[ { dataURL: "your uploaded image URL" } ]}
```
Hope it helpful for you.

**Comment by Shreykhanna** [comment]
Hey, thanks for reply. I solved it later. The issue was i was not passing right variable. 

Cheers
