### ISSUE TITLE
Removed images cannot be re-added

### ISSUE THREAD

**Issue by dougwigg** [vutoan266/react-images-uploading#9]
First, thanks for this package!  nicely done :)

The error I'm seeing ( which might be considered a feature in some cases ) is that if you add 1 image, then remove it, you cannot re-add that same image ( when selecting a single image at a time  ).

The error can be repro-ed on the demo page ( add 1 image, remove it, try to re-add it ).

In my app ( where users are uploading a profile pic ) this could be confusing if someone changes their mind and then can't re-add an image.

**Comment by vutoan266** [comment]
Hi bro,
Thanks for your feedback.
The above issue I have fixed and release in version [2.2.1](https://www.npmjs.com/package/react-images-uploading)  also upgrade dependency version on codesandbox demo :D

**Comment by dougwigg** [comment]
Hey thanks!  that was fast :)
