### ISSUE TITLE
custom xóa file làm sao vậy mấy bác 

### ISSUE THREAD

**Issue by raidichu** [vutoan266/react-images-uploading#90]
Giờ em muốn xóa ảnh trong list link từ server trả về nhưng ko custom dc cái delete của nó

**Comment by vutoan266** [comment]
Hi @raidichu, chưa hiểu ý bạn lắm, có thể cho mình codesandbox đơn giản hoặc giải thích cụ thể hơn được không.

**Comment by davidnguyen179** [comment]
should we make this conversation by English? I think it's good for other ones know the issue

**Comment by raidichu** [comment]
cám ơn các bác e sửa dc r
thank you
