### ISSUE TITLE
What should I pass to the backend to save the actual image file?

### ISSUE THREAD

**Issue by Jake-Mulhern** [vutoan266/react-images-uploading#98]
I am using this package and everything on the frontend works great.  I wrote a handleUpload function that should pass the file to my django backend and save it in the database, however I am getting errors saying that it is passing "application/json" and not "image/jpeg".

Any help here would be appreciated.

```
  const handleUpload = (avatar: any) => {
    const response = axiosInstance.post('/avatar-upload/', {
      file: avatar.data_url
    });
  };
```

**Comment by vutoan266** [comment]
Hi @Jake-Mulhern-Bixly ,
For your case, you could get `avatar.file` to pass to your BE.
Thank bro!
