### ISSUE TITLE
Version Conflict

### ISSUE THREAD

**Issue by NohaAshraf85** [vutoan266/react-images-uploading#99]
Hi, i was so excited when i found this package and i started using it for my react project, but then i got an error 

> because it conflicted with the current version of React (17.0.2) is there a solution for this?

>

**Comment by vutoan266** [comment]
Hi @NohaAshraf85,

When did you get this error message? in NPM installing phase?
I propose that relate to the new behavior of NPM. Check [here](https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh)

You could bypass this error by installing our package: 
`npm install react-images-uploading --legacy-peer-deps`

Thank you!

**Comment by vutoan266** [comment]
I have just upgraded the peerDepedency of react/react-dom version. Please update to react-images-uploading@3.1.5
Thank you!
